//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StacjaDiagnostyczna
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pojazd()
        {
            this.Przeglad = new HashSet<Przeglad>();
        }
    
        public int Id_Pojazdu { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Numer_Rejestracyjny { get; set; }
        public int Id_Wlasciciela { get; set; }
        public decimal Przebieg { get; set; }
        public int Rocznik { get; set; }
    
        public virtual Wlasciciel Wlasciciel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przeglad> Przeglad { get; set; }
    }
}
