//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StacjaDiagnostyczna
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Przeglad
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id_Przegladu { get; set; }
        public int ID_Pojazdu { get; set; }
        public System.DateTime Data { get; set; }
        public int ID_Diagnosty { get; set; }
        public bool Wynik { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Diagnosta Diagnosta { get; set; }
        public virtual Pojazd Pojazd { get; set; }
    }
}
